[package]
name    = "nalgebra"
version = "0.23.1"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "Linear algebra library with transformations and statically-sized or dynamically-sized matrices."
documentation = "https://nalgebra.org/rustdoc/nalgebra/index.html"
homepage = "https://nalgebra.org"
repository = "https://github.com/rustsim/nalgebra"
readme = "README.md"
categories = [ "science" ]
keywords = [ "linear", "algebra", "matrix", "vector", "math" ]
license = "Apache-2.0"
edition = "2018"

exclude = ["/ci/*", "/.travis.yml", "/Makefile"]

[lib]
name = "nalgebra"
path = "src/lib.rs"

[features]
default         = [ "std" ]
std             = [ "matrixmultiply", "rand/std", "rand_distr", "simba/std" ]
stdweb          = [ "rand/stdweb" ]
arbitrary       = [ "quickcheck" ]
borsh-serialize = [ "borsh" ]
serde-serialize = [ "serde", "num-complex/serde" ]
abomonation-serialize = [ "abomonation" ]
sparse = [ ]
debug = [ "approx/num-complex", "rand/std" ]
alloc = [ ]
io = [ "pest", "pest_derive" ]
compare = [ "matrixcompare-core" ]
libm = [ "simba/libm" ]
libm-force = [ "simba/libm_force" ]


[dependencies]
typenum        = "1.12"
generic-array  = "0.14"
borsh          = { version = "0.7", optional = true }
rand           = { version = "0.7", default-features = false }
num-traits     = { version = "0.2", default-features = false }
num-complex    = { version = "0.3", default-features = false }
num-rational   = { version = "0.3", default-features = false }
approx         = { version = "0.4", default-features = false }
simba          = { version = "0.3", default-features = false }
alga           = { version = "0.9", default-features = false, optional = true }
rand_distr     = { version = "0.3", optional = true }
matrixmultiply = { version = "0.2", optional = true }
serde          = { version = "1.0", default-features = false, features = [ "derive" ], optional = true }
abomonation    = { version = "0.7", optional = true }
mint           = { version = "0.5", optional = true }
quickcheck     = { version = "0.9", optional = true }
pest           = { version = "2", optional = true }
pest_derive    = { version = "2", optional = true }
matrixcompare-core = { version = "0.1", optional = true }

[dev-dependencies]
serde_json = "1.0"
rand_xorshift = "0.2"
rand_isaac = "0.2"
### Uncomment this line before running benchmarks.
### We can't just let this uncommented because that would break
### compilation for #[no-std] because of the terrible Cargo bug
### https://github.com/rust-lang/cargo/issues/4866
#criterion = "0.2.10"

# For matrix comparison macro
matrixcompare = "0.1.3"

[workspace]
members = [ "nalgebra-lapack", "nalgebra-glm" ]

[[bench]]
name = "nalgebra_bench"
harness = false
path = "benches/lib.rs"

[profile.bench]
lto = true
